version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./sqlfiles:/docker-entrypoint-initdb.d
  server_python:
    container_name: server_python
    restart: always
    image: python
    volumes:
      - ./server_python:/server_python
    build:
      context: ./server_python
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - ADMIN_PASS=${ADMIN_PASS}
    depends_on:
      - db
  react:
    restart: always
    image: react
    container_name: react
    build:
      context: ./react-app
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./react-app:/react-app
      - /react-app/node_modules
    depends_on:
      - server_python